apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fond-polimark-com-tls
spec:
  secretName: fond-polimark-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fond-polimark.com
  dnsNames:
    - fond-polimark.com
    - www.fond-polimark.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fond-polimark.com
          - www.fond-polimark.com
