apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-multi.com
  dnsNames:
    - fond-polimark.com
    - www.fond-polimark.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - pond-polimark.com
          - www.fond-polimark.com
